# Generated by Django 5.1.6 on 2025-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='person',
        ),
        migrations.AddField(
            model_name='car',
            name='person',
            field=models.ManyToManyField(to='home.person'),
        ),
    ]
